### ISSUE TITLE
decode error when running LM

### ISSUE THREAD

**Issue by tinus** [RedRise/lm#10]
Traceback (most recent call last):
  File "/usr/local/bin/lm", line 1418, in <module>
    files = LM.get_files(args)
  File "/usr/local/bin/lm", line 1166, in get_files
    real_path, True, *self.file_ext ) )
  File "/usr/local/bin/lm", line 110, in filelist
    result.extend( filelist( f, True, *ext) )
  File "/usr/local/bin/lm", line 104, in filelist
    alist = [ os.path.abspath(os.path.join(dir,f)) for f in os.listdir( dir )]
  File "/usr/lib/python2.6/posixpath.py", line 70, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 18: ordinal not in range(128)

**Comment by RedRise** [comment]
Could you re-run it with --debug option and send me the output log file ~/.lm/lm_log.txt by mail (Polluxxx at gmail dot com) or post it here?

Thanks

**Comment by tinus** [comment]
2012-03-12 17:29:13,665: LM UTIL - INFO - argparse namespace: Namespace(alphabetical=False, confirm=False, debug=True, delete_cache=False, download=None, files=[], filter=None, long=False, outline=False, reset=False, reverse=False, show=False, show_imdb=False, upload=False, version=False, very_long=False)
2012-03-12 17:29:13,666: LM UTIL - INFO - arg files type: <type 'str'>
2012-03-12 17:29:13,666: LM UTIL - INFO - file system encoding: UTF-8
2012-03-12 17:29:13,667: LM UTIL - INFO - system encoding: ascii
2012-03-12 17:29:13,667: LM UTIL - INFO - locale encoding: UTF-8
2012-03-12 17:29:13,668: LM - INFO - LM initialization
2012-03-12 17:29:13,668: LM - INFO - loading cache_path
2012-03-12 17:29:13,669: LM - INFO - loading cache_hash
2012-03-12 17:29:13,830: LM - INFO - interpreting file/dir argument

**Comment by RedRise** [comment]
I made a slight update on script. Could you try it (dowload the script directly, dont use the Download Packages menu).

**Comment by tinus** [comment]
I tried it, same results

If I run it in a directory with just 1 movie it works fine but when I run it in the folder that I store my movies in it give the error.

**Comment by tinus** [comment]
sorry not the same results. 1 line number is different:

Traceback (most recent call last):
  File "/usr/local/bin/lm", line 1418, in <module>
    files = LM.get_files(args)
  File "/usr/local/bin/lm", line 1166, in get_files
    real_path, True, *self.file_ext ) )
  File "/usr/local/bin/lm", line 110, in filelist
    result.extend( filelist( f, True, *ext) )
  File "/usr/local/bin/lm", line 104, in filelist
    alist = [ os.path.abspath(os.path.join(dir,f)) for f in os.listdir( dir )]
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 18: ordinal not in range(128)

**Comment by RedRise** [comment]
And the log file (--debug) gives the same result too?

**Comment by tinus** [comment]
2012-03-12 18:21:44,020: LM UTIL - INFO - argparse namespace: Namespace(alphabetical=False, confirm=False, debug=True, delete_cache=False, download=None, files=[], filter=None, long=False, outline=False, reset=False, reverse=False, show=False, show_imdb=False, upload=False, version=False, very_long=False)
2012-03-12 18:21:44,021: LM UTIL - INFO - arg files type: <type 'unicode'>
2012-03-12 18:21:44,022: LM UTIL - INFO - file system encoding: UTF-8
2012-03-12 18:21:44,022: LM UTIL - INFO - system encoding: ascii
2012-03-12 18:21:44,023: LM UTIL - INFO - locale encoding: UTF-8
2012-03-12 18:21:44,023: LM - INFO - LM initialization
2012-03-12 18:21:44,024: LM - INFO - loading cache_path
2012-03-12 18:21:44,025: LM - INFO - cache_path file loaded successfully
2012-03-12 18:21:44,025: LM - INFO - loading cache_hash
2012-03-12 18:21:44,027: LM - INFO - cache_hash file loaded successfully
2012-03-12 18:21:44,206: LM - INFO - interpreting file/dir argument

**Comment by RedRise** [comment]
All is about a character encoding issue, sorry for that. Not so easy to handle because I can't reproduce the error on my computer.
If its possible, could you precise on your call a specific directory, that contains special characters (éêàç...).
./lm.py sample_dir_ééé --debug
To produce a more comprehensive log file?
Regards, and thanks for your help.
Red Rise

**Comment by tinus** [comment]
2012-03-12 18:28:16,592: LM UTIL - INFO - argparse namespace: Namespace(alphabetical=False, confirm=False, debug=True, delete_cache=False, download=None, files=['sample_dir_\xc3\xa9\xc3\xa9\xc3\xa9'], filter=None, long=False, outline=False, reset=False, reverse=False, show=False, show_imdb=False, upload=False, version=False, very_long=False)
2012-03-12 18:28:16,594: LM UTIL - INFO - arg files type: <type 'str'>
2012-03-12 18:28:16,594: LM UTIL - INFO - file system encoding: UTF-8
2012-03-12 18:28:16,595: LM UTIL - INFO - system encoding: ascii
2012-03-12 18:28:16,595: LM UTIL - INFO - locale encoding: UTF-8
2012-03-12 18:28:16,596: LM - INFO - LM initialization
2012-03-12 18:28:16,596: LM - INFO - loading cache_path
2012-03-12 18:28:16,597: LM - INFO - cache_path file loaded successfully
2012-03-12 18:28:16,598: LM - INFO - loading cache_hash
2012-03-12 18:28:16,599: LM - INFO - cache_hash file loaded successfully
2012-03-12 18:28:16,769: LM - INFO - interpreting file/dir argument
2012-03-12 18:28:16,781: LM - INFO - saving caches
2012-03-12 18:28:16,782: LM - INFO - synchronizing caches
2012-03-12 18:28:16,782: LM - INFO - saving cache_path
2012-03-12 18:28:16,783: LM - INFO - cache_path saved
2012-03-12 18:28:16,784: LM - INFO - saving cache_hash
2012-03-12 18:28:16,786: LM - INFO - cache_hash saved

**Comment by tinus** [comment]
this is the weirdest looking folder name I could find, but when I entered it on its own on the commandline it worked fine:

2012-03-12 18:36:51,241: LM UTIL - INFO - argparse namespace: Namespace(alphabetical=False, confirm=False, debug=True, delete_cache=False, download=None, files=['./The_Mothman_Prophecies_2002_DVDRIp_Xvid&acirc;\xc2\x80\xc2\x93THC'], filter=None, long=False, outline=False, reset=False, reverse=False, show=False, show_imdb=False, upload=False, version=False, very_long=False)
2012-03-12 18:36:51,242: LM UTIL - INFO - arg files type: <type 'str'>
2012-03-12 18:36:51,243: LM UTIL - INFO - file system encoding: UTF-8
2012-03-12 18:36:51,244: LM UTIL - INFO - system encoding: ascii
2012-03-12 18:36:51,245: LM UTIL - INFO - locale encoding: UTF-8
2012-03-12 18:36:51,246: LM - INFO - LM initialization
2012-03-12 18:36:51,246: LM - INFO - loading cache_path
2012-03-12 18:36:51,248: LM - INFO - cache_path file loaded successfully
2012-03-12 18:36:51,248: LM - INFO - loading cache_hash
2012-03-12 18:36:51,250: LM - INFO - cache_hash file loaded successfully
2012-03-12 18:36:51,434: LM - INFO - interpreting file/dir argument
2012-03-12 18:36:51,438: LM - INFO - saving caches
2012-03-12 18:36:51,439: LM - INFO - synchronizing caches
2012-03-12 18:36:51,439: LM - INFO - saving cache_path
2012-03-12 18:36:51,441: LM - INFO - cache_path saved
2012-03-12 18:36:51,442: LM - INFO - saving cache_hash
2012-03-12 18:36:51,446: LM - INFO - cache_hash saved
The Mothman Prophecies (The Mothman Prophecies 2002 DVDRIp Xvid-THC.avi)

**Comment by tinus** [comment]
I think I found the offending filename:

Alain Chabat - Pr?te-moi ta main (2006) - DvdRip - french - Calvar75 .avi

running lm in this folder gives:

2012-03-12 18:45:12,937: LM UTIL - INFO - argparse namespace: Namespace(alphabetical=False, confirm=False, debug=True, delete_cache=False, download=None, files=['prete_moi_ta_main(2006)/'], filter=None, long=False, outline=False, reset=False, reverse=False, show=False, show_imdb=False, upload=False, version=False, very_long=False)
2012-03-12 18:45:12,938: LM UTIL - INFO - arg files type: <type 'str'>
2012-03-12 18:45:12,939: LM UTIL - INFO - file system encoding: UTF-8
2012-03-12 18:45:12,939: LM UTIL - INFO - system encoding: ascii
2012-03-12 18:45:12,940: LM UTIL - INFO - locale encoding: UTF-8
2012-03-12 18:45:12,941: LM - INFO - LM initialization
2012-03-12 18:45:12,941: LM - INFO - loading cache_path
2012-03-12 18:45:12,942: LM - INFO - cache_path file loaded successfully
2012-03-12 18:45:12,943: LM - INFO - loading cache_hash
2012-03-12 18:45:12,945: LM - INFO - cache_hash file loaded successfully
2012-03-12 18:45:13,109: LM - INFO - interpreting file/dir argument
Traceback (most recent call last):
  File "/usr/local/bin/lm", line 1418, in <module>
    files = LM.get_files(args)
  File "/usr/local/bin/lm", line 1166, in get_files
    real_path, True, *self.file_ext ) )
  File "/usr/local/bin/lm", line 104, in filelist
    alist = [ os.path.abspath(os.path.join(dir,f)) for f in os.listdir( dir )]
  File "/usr/lib/python2.7/posixpath.py", line 69, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 17: ordinal not in range(128)

**Comment by RedRise** [comment]
Thanks, I updated logging faciolities, to be more precise.
Could you use it and return your last example again?
Regards, Red Rise

**Comment by tinus** [comment]
Oh I am sorry, I renamed the file so I could see what lm does and how it works.
 didn't think about it, sorry.

It does work like a charm now, so thanks.
Should I encounter another french movie I will let you know :)

**Comment by RedRise** [comment]
This issue should be solved with last update.
Filenames not encoded in default file system encoding are ignored (but can be seen in --debug mode)

**Comment by tinus** [comment]
Cool, thanks
